plot_line() to plot a small sphere if a single coordinate is passed
sunpy/sunkit-pyvista pull request #29
Opened 2021-06-28 17:05 UTC by jeffreypaul15

- `plot_line()` is changed to `plot_coordinates()`
- If the user passes a single coordinate, the plot produced is a small sphere (0.05 times `R_sun`)

![image](https://user-images.githubusercontent.com/50923538/123676105-22ab2180-d861-11eb-8d4c-242006d6e3a5.png)

- [ ] Tests are to be added
- [ ] Example to be re-written to plot on the brightest coordinate?

2021-06-29 08:33 UTC, nabobalis commented
> * [ ]  Example to be re-written to plot on the brightest coordinate?

Why not? Could be nice but would we want a sphere to cover the part fully?

2021-06-29 10:49 UTC, jeffreypaul15 commented
> Why not? Could be nice but would we want a sphere to cover the part fully?

Thought it would be consistent with sunpy's examples but there's no need to I suppose

2021-06-29 11:02 UTC, nabobalis commented
> > Why not? Could be nice but would we want a sphere to cover the part fully?
> 
> Thought it would be consistent with sunpy's examples but there's no need to I suppose

Lets do it.

2021-06-30 16:34 UTC, dstansby requested changes
Looks good, but the test just needs fixing

2021-06-30 17:01 UTC, jeffreypaul15 commented
> Looks good, but the test just needs fixing

I'm sorry I don't understand what has to be fixed

2021-06-30 17:18 UTC, nabobalis commented
> > Looks good, but the test just needs fixing
> 
> I'm sorry I don't understand what has to be fixed

```
>       assert plotter.plotter.mesh.n_cells == 1
E       assert 1680 == 1
```

2021-06-30 21:55 UTC, nabobalis commented on changelog/29.feature.rst
> +which also allows for a sphere with given ``radius`` to be plotted if a sinlge coordinate is passed to it.
```suggestion
which also allows for a sphere with given ``radius`` to be plotted if a singe coordinate is passed to it.
```

2021-06-30 21:56 UTC, nabobalis commented on sunkit_pyvista/plotter.py
> +        radius : `int`
```suggestion
        radius : `int`, optional
```

2021-06-30 21:56 UTC, nabobalis commented on sunkit_pyvista/plotter.py
>          Notes
```suggestion

        Notes
```

2021-07-01 11:59 UTC, dstansby approved these changes

2021-07-01 11:59 UTC, merged